In [1]:
import pandas as pd

In [2]:
import os
os.getcwd()

'u:\\cis-reg\\scripts'

# Data from Gsponer 2016

this script parses data from Gsponer training and testing datasets

## Proteins from train dataset

In [2]:
# CRE-containing proteins in training dataset (Gsponer 2016)
# It contains both disordered and structured CREs
cre_train = pd.read_excel('../raw_data/1-s2.0-S2405471216300345-mmc2.xlsx', skiprows= 3)

In [3]:
cre_train.columns = cre_train.columns.str.lower()
cre_train.rename(columns= {'uniprot accession number': 'uniprot_acc'}, inplace= True)

In [4]:
cre_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253 entries, 0 to 252
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         245 non-null    object
 1   uniprot_acc  120 non-null    object
 2   species      120 non-null    object
 3   cre          120 non-null    object
 4   references   120 non-null    object
dtypes: object(5)
memory usage: 10.0+ KB

In [5]:
# Drop bibliography and empty rows
cre_train = cre_train.dropna()
cre_train

,name,uniprot_acc,species,cre,references
0,DNMT1,UniProt:P13864,M. musculus,699-733,"(Song et al., 2011; Trudeau et al., 2013)"
1,TBP,UniProt:P20226,H. sapiens,1-55,"(Kuddus and Schmidt, 1993; Trudeau et al., 2013)"
2,TAK1,UniProt:Q62073,M. musculus,1-22,"(Yamaguchi et al., 1995)"
3,SNF1,UniProt:P06782,S. crevisiae,392-495,"(Jiang and Carlson, 1997; Trudeau et al., 2013)"
4,TSE1,UniProt:P10644,H. sapiens,1-98,"(Francis et al., 2002)"
...,...,...,...,...,...
118,FimH,UniProt:Q0T8Y8,E. coli,181-279,"(Le Trong et al., 2010; Trudeau et al., 2013)"
119,Intersectin-1L,UniProt:Q9Z0R4,M. musculus,1151-1205,"(Ahmad and Lim, 2010; Trudeau et al., 2013)"
120,YKT6,UniProt:Q5EGY4,R. norvegicus,46-95,"(Wen et al., 2010)"
121,IRF-7,UniProt:Q92985,H. sapiens,404-466,"(Sathish et al., 2011)"
122,hPDE5,UniProt:O76074,H. sapiens,1-535,"(Francis et al., 2011)"

In [6]:
# Index of the position where the other table beggins
ix = cre_train.index[cre_train.name == 'Name'].to_list()[0]

In [7]:
# df of Proteins with a disordered CREs
cre_train_disordered = cre_train.loc[:ix-1]
cre_train_disordered['module'] = 'd'

<ipython-input-7-2c70911066d7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cre_train_disordered['module'] = 'd'

In [8]:
# df of proteins with structured CREs
#  ix is the header
cre_train_structured = cre_train.loc[ix+1:]
cre_train_structured['module'] = 's'

<ipython-input-8-5b1b9509b0eb>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cre_train_structured['module'] = 's'

In [9]:
cre_train = pd.concat([cre_train_disordered, cre_train_structured])
cre_train

,name,uniprot_acc,species,cre,references,module
0,DNMT1,UniProt:P13864,M. musculus,699-733,"(Song et al., 2011; Trudeau et al., 2013)",d
1,TBP,UniProt:P20226,H. sapiens,1-55,"(Kuddus and Schmidt, 1993; Trudeau et al., 2013)",d
2,TAK1,UniProt:Q62073,M. musculus,1-22,"(Yamaguchi et al., 1995)",d
3,SNF1,UniProt:P06782,S. crevisiae,392-495,"(Jiang and Carlson, 1997; Trudeau et al., 2013)",d
4,TSE1,UniProt:P10644,H. sapiens,1-98,"(Francis et al., 2002)",d
...,...,...,...,...,...,...
118,FimH,UniProt:Q0T8Y8,E. coli,181-279,"(Le Trong et al., 2010; Trudeau et al., 2013)",s
119,Intersectin-1L,UniProt:Q9Z0R4,M. musculus,1151-1205,"(Ahmad and Lim, 2010; Trudeau et al., 2013)",s
120,YKT6,UniProt:Q5EGY4,R. norvegicus,46-95,"(Wen et al., 2010)",s
121,IRF-7,UniProt:Q92985,H. sapiens,404-466,"(Sathish et al., 2011)",s
122,hPDE5,UniProt:O76074,H. sapiens,1-535,"(Francis et al., 2011)",s

In [10]:
# Select only the uniprot accesion
cre_train.uniprot_acc = cre_train.uniprot_acc.apply(lambda x: x.split(':')[1])

In [11]:
cre_train.species.value_counts()

H. sapiens                       66
M. musculus                      21
R. norvegicus                     5
G. gallus                         4
E. coli                           3
S. cerevisiae                     3
D. melanogaster                   2
C. griseus                        1
A. castellanii                    1
S. crevisiae                      1
S. vulgare                        1
C. glutamicum                     1
S. cerevisiae                     1
C. elegans                        1
S. pombe                          1
D. melanogaster                   1
H. sapiens                        1
Hepatitis C virus genotype 1b     1
C. elegans                        1
B. amyloliquefaciens              1
L. monocytogenes                  1
D. rerio                          1
Name: species, dtype: int64

In [12]:
# strip blank spaces
cre_train.species = cre_train.species.str.strip()

In [13]:
cre_train.species.value_counts()

H. sapiens                       67
M. musculus                      21
R. norvegicus                     5
S. cerevisiae                     4
G. gallus                         4
E. coli                           3
D. melanogaster                   3
C. elegans                        2
A. castellanii                    1
S. crevisiae                      1
S. vulgare                        1
C. griseus                        1
S. pombe                          1
Hepatitis C virus genotype 1b     1
C. glutamicum                     1
B. amyloliquefaciens              1
L. monocytogenes                  1
D. rerio                          1
Name: species, dtype: int64

see

In [14]:
# One protein could have one or more CREs, separated by ","
cre_train.cre = cre_train.cre.str.split(",")
cre_train = cre_train.explode("cre")

In [15]:
# Format start and end aa
cre_train['start_aa'] = cre_train.cre.apply(lambda x: x.split('-')[0]).astype(int)
cre_train['end_aa'] = cre_train.cre.apply(lambda x: x.split('-')[1]).astype(int)
cre_train.drop(columns= 'cre', inplace= True)

In [16]:
cre_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 135 entries, 0 to 122
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         135 non-null    object
 1   uniprot_acc  135 non-null    object
 2   species      135 non-null    object
 3   references   135 non-null    object
 4   module       135 non-null    object
 5   start_aa     135 non-null    int32
 6   end_aa       135 non-null    int32
dtypes: int32(2), object(5)
memory usage: 7.4+ KB

## Proteins from test dataset
to do: format correctly start and end

In [35]:
cre_test = pd.read_excel('../raw_data/1-s2.0-S2405471216300345-mmc3.xlsx', skiprows= 3)

In [36]:
# Format cols
cre_test.columns = cre_test.columns.str.lower()
cre_test.rename(columns= {'uniprot accession number': 'uniprot_acc', 'crea': 'cre'}, inplace= True)

In [37]:
# Drop references
ix = cre_test.index[cre_test.name == 'References'].to_list()[0]
cre_test = cre_test.loc[:ix-1]
# Drop empty rows
cre_test = cre_test.dropna()

In [38]:
cre_test

,name,uniprot_acc,species,cre,references
0,CAMKK2,UniProt:Q96RR4,H. sapiens,471-499,"(Green et al., 2011; Lin and DeFea, 2013)"
1,STIM2,UniProt:Q9P246,H. sapiens,67-131,"(Trudeau et al., 2013; Zheng et al., 2011)"
2,NCF-1,UniProt:P14598,H. sapiens,287-329,"(Trudeau et al., 2013; Yuzawa et al., 2004)"
3,Kinesin-1,UniProt:P17210,D. melanogaster,937-975,"(Kaan et al., 2011; Trudeau et al., 2013)"
4,p53,UniProt:P04637,H. sapiens,364-393,"(Ko and Prives, 1996; Trudeau et al., 2013)"
5,GLP-1,UniProt:P13508,C. elegans,1174-1295,"(Mango et al., 1991)"
6,FGFR3,UniProt:P22607,H. sapiens,126-145,"(Kalinina et al., 2012)"
7,ACAP1,UniProt:Q15027,H. sapiens,525-568,"(Bai et al., 2012)"
8,STING,UniProt:Q86WV6,H. sapiens,343-379,"(Yin et al., 2012)"
9,Vta1,UniProt:Q06263,S. cerevisiae,183-266,"(Norgan et al., 2013)"
10,Zuotin,UniProt:P32527,S. cerevisiae,348-364,"(Ducett et al., 2013)"
11,p65,UniProt:Q04206,H. sapiens,313-550,"(Trudeau et al., 2013)"
12,Zyxin,UniProt:Q15942,H. sapiens,1-130,"(Hansen and Kwiatkowski, 2013)"
13,PLCÎ²3,UniProt:Q01970,H. sapiens,471-575,"(Lyon et al., 2014)"
14,RAD26 homolog,UniProt:Q9UR24,S. pombe,825-973,"(Wang et al., 2014)"
15,PLK-4,UniProt:O97143,D. melanogaster,318-380,"(Klebba et al., 2015)"
18,Name,UniProt Accession Number,Species,CRE,References
19,p38,UniProt:P46108,H. sapiens,239-294,"(Sarkar et al., 2011)"
20,SHP2,UniProt:Q06124,H. sapiens,6-81,"(Darian et al., 2011)"
21,LapD,UniProt:Q3KK31,P. fluorescens,171-394,"(Navarro et al., 2011; Trudeau et al., 2013)"
22,Cin85,UniProt:Q96B97,H. sapiens,267-328,"(Philippe et al., 2011)"
23,SmyD3,UniProt:Q9H7B4,H. sapiens,280-428,"(Sirinupong et al., 2011; Trudeau et al., 2013)"
24,Smurf2,UniProt:Q9HAU4,H. sapiens,14-98,"(Lu et al., 2011)"
25,ROR2,UniProt:Q01974,H. sapiens,633-646,"(Artim et al., 2012)"
26,Cbl,UniProt:P22681,H. sapiens,353-435,"(Dou et al., 2012)"
27,Ste5,UniProt:P32917,S. cerevisiae,"367-517, 544-592","(Zalatan et al., 2012)"
28,RSK1,UniProt:Q15418,H. sapiens,687-706,"(Li et al., 2012)"
29,Pacsin-1,UniProt:Q9BY11,H. sapiens,392-442,"(Goh et al., 2012)"
30,NLRC4,UniProt:Q3UP24,M. musculus,299-355,"(Hu et al., 2013)"
31,Park2,UniProt:Q9JK66,R. norvegicus,410-465,"(Byrd and Weissman, 2013)"
32,EB1,UniProt:Q15691,H. sapiens,189-268,"(Kanaba et al., 2013)"
33,gp47,UniProt:P04521,Enterobacteria phage T4,303-320,"(Gao and Nelson, 2014)"
34,nPKC-iota,UniProt:P41743,H. sapiens,123-140,"(Ivey et al., 2014)"

In [39]:
ix = cre_test.index[cre_test.name == 'Name'].to_list()[0]
cre_test_disordered = cre_test.loc[:ix-1]
cre_test_disordered['module'] = 'd'
cre_test_structured = cre_test.loc[ix+1:]
cre_test_structured['module'] = 's'

<ipython-input-39-253c130772c8>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cre_test_disordered['module'] = 'd'
<ipython-input-39-253c130772c8>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cre_test_structured['module'] = 's'

In [40]:
cre_test = pd.concat([cre_test_disordered, cre_test_structured])

In [41]:
# strip blanks
cre_test.species = cre_test.species.str.strip()

In [42]:
cre_test.species.value_counts()

H. sapiens                 21
S. cerevisiae               3
D. melanogaster             2
S. pombe                    1
C. elegans                  1
M. musculus                 1
P. fluorescens              1
R. norvegicus               1
Enterobacteria phage T4     1
Name: species, dtype: int64

In [43]:
# Select only the uniprot accesion
cre_test.uniprot_acc = cre_test.uniprot_acc.apply(lambda x: x.split(':')[1])

In [44]:
# Some proteins may have more than one CRE module
cre_test.cre = cre_test.cre.str.split(',')
cre_test = cre_test.explode('cre')

In [45]:
# Format start and end aa
cre_test['start_aa'] = cre_test.cre.apply(lambda x: x.split('-')[0]).astype(int)
cre_test['end_aa'] = cre_test.cre.apply(lambda x: x.split('-')[1]).astype(int)
cre_test.drop(columns= 'cre', inplace= True)

In [46]:
cre_test

,name,uniprot_acc,species,references,module,start_aa,end_aa
0,CAMKK2,Q96RR4,H. sapiens,"(Green et al., 2011; Lin and DeFea, 2013)",d,471,499
1,STIM2,Q9P246,H. sapiens,"(Trudeau et al., 2013; Zheng et al., 2011)",d,67,131
2,NCF-1,P14598,H. sapiens,"(Trudeau et al., 2013; Yuzawa et al., 2004)",d,287,329
3,Kinesin-1,P17210,D. melanogaster,"(Kaan et al., 2011; Trudeau et al., 2013)",d,937,975
4,p53,P04637,H. sapiens,"(Ko and Prives, 1996; Trudeau et al., 2013)",d,364,393
5,GLP-1,P13508,C. elegans,"(Mango et al., 1991)",d,1174,1295
6,FGFR3,P22607,H. sapiens,"(Kalinina et al., 2012)",d,126,145
7,ACAP1,Q15027,H. sapiens,"(Bai et al., 2012)",d,525,568
8,STING,Q86WV6,H. sapiens,"(Yin et al., 2012)",d,343,379
9,Vta1,Q06263,S. cerevisiae,"(Norgan et al., 2013)",d,183,266
10,Zuotin,P32527,S. cerevisiae,"(Ducett et al., 2013)",d,348,364
11,p65,Q04206,H. sapiens,"(Trudeau et al., 2013)",d,313,550
12,Zyxin,Q15942,H. sapiens,"(Hansen and Kwiatkowski, 2013)",d,1,130
13,PLCÎ²3,Q01970,H. sapiens,"(Lyon et al., 2014)",d,471,575
14,RAD26 homolog,Q9UR24,S. pombe,"(Wang et al., 2014)",d,825,973
15,PLK-4,O97143,D. melanogaster,"(Klebba et al., 2015)",d,318,380
19,p38,P46108,H. sapiens,"(Sarkar et al., 2011)",s,239,294
20,SHP2,Q06124,H. sapiens,"(Darian et al., 2011)",s,6,81
21,LapD,Q3KK31,P. fluorescens,"(Navarro et al., 2011; Trudeau et al., 2013)",s,171,394
22,Cin85,Q96B97,H. sapiens,"(Philippe et al., 2011)",s,267,328
23,SmyD3,Q9H7B4,H. sapiens,"(Sirinupong et al., 2011; Trudeau et al., 2013)",s,280,428
24,Smurf2,Q9HAU4,H. sapiens,"(Lu et al., 2011)",s,14,98
25,ROR2,Q01974,H. sapiens,"(Artim et al., 2012)",s,633,646
26,Cbl,P22681,H. sapiens,"(Dou et al., 2012)",s,353,435
27,Ste5,P32917,S. cerevisiae,"(Zalatan et al., 2012)",s,367,517
27,Ste5,P32917,S. cerevisiae,"(Zalatan et al., 2012)",s,544,592
28,RSK1,Q15418,H. sapiens,"(Li et al., 2012)",s,687,706
29,Pacsin-1,Q9BY11,H. sapiens,"(Goh et al., 2012)",s,392,442
30,NLRC4,Q3UP24,M. musculus,"(Hu et al., 2013)",s,299,355
31,Park2,Q9JK66,R. norvegicus,"(Byrd and Weissman, 2013)",s,410,465
32,EB1,Q15691,H. sapiens,"(Kanaba et al., 2013)",s,189,268
33,gp47,P04521,Enterobacteria phage T4,"(Gao and Nelson, 2014)",s,303,320
34,nPKC-iota,P41743,H. sapiens,"(Ivey et al., 2014)",s,123,140

### Check overlap between sets

In [47]:
cre_train[cre_train.uniprot_acc.isin(cre_test.uniprot_acc)]

Empty DataFrame
Columns: [name, uniprot_acc, species, references, module, start_aa, end_aa, dataset]
Index: []

In [48]:
cre_test[cre_test.uniprot_acc.isin(cre_train.uniprot_acc)] # Ok

Empty DataFrame
Columns: [name, uniprot_acc, species, references, module, start_aa, end_aa]
Index: []

## Make only one dataset

In [49]:
cre_train['dataset'] = 'train'
cre_test['dataset'] = 'test'

In [50]:
cre_dataset = pd.concat([cre_train, cre_test])

### Add an ID for each CRE

In [51]:
cre_dataset["id_cre"] = range(1, cre_dataset.shape[0] + 1)

In [52]:
# Check data type
cre_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 168 entries, 0 to 34
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         168 non-null    object
 1   uniprot_acc  168 non-null    object
 2   species      168 non-null    object
 3   references   168 non-null    object
 4   module       168 non-null    object
 5   start_aa     168 non-null    int32
 6   end_aa       168 non-null    int32
 7   dataset      168 non-null    object
 8   id_cre       168 non-null    int32
dtypes: int32(3), object(6)
memory usage: 11.2+ KB

### Save

In [54]:
# An entry is duplicated because it poses two CREs
#cre_dataset[cre_dataset.uniprot_acc.duplicated()]

In [55]:
cre_dataset.uniprot_acc.nunique() # ok

151

In [56]:
cre_dataset[cre_dataset.uniprot_acc == 'Q0T8Y8']

,name,uniprot_acc,species,references,module,start_aa,end_aa,dataset,id_cre
118,FimH,Q0T8Y8,E. coli,"(Le Trong et al., 2010; Trudeau et al., 2013)",s,181,279,train,131

Q0T8Y8 is obsolet in UniProtKB  
Must be replaced by P08191 (current)

In [57]:
cre_dataset.replace('Q0T8Y8', 'P08191', inplace= True)

In [61]:
# List with uniprot accessions
lst = list(cre_dataset.uniprot_acc.unique())
# Save it
output_list = open('../datasets/uniprots_list.txt', 'w')

for l in lst:
    output_list.write(l + '\n')

output_list.close()

In [62]:
c = 0
for l in lst:
    c += 1
print(c)

151

In [59]:
# Save dataset
#cre_dataset.to_csv('../datasets/cre_dataset.csv', index= False)