In [2]:
import pandas as pd
import json
import re
import pyranges as pr
import matplotlib.pyplot as plt

In [3]:
# Cis proteins
cre_dataset = pd.read_csv('../datasets/cre_dataset.csv')

In [4]:
# Create an unique list with the uniprot accessions
up = [ up for up in cre_dataset.uniprot_acc.unique()]

## FLIPPER data
an automatic method for the detection of structurally linear sub-regions or peptides that interact with another chain in a protein complex.

### Json file

In [5]:
# Regex for uniprot accesions
pattern = re.compile('[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}') # uniprot accession patterns

In [6]:
#examp = ["A0A0D6HTJ9", "P0A825", "Q8I566"]

In [7]:
# with open("../raw_data/example.txt", "r") as f:
#     for line in f:
#         try:
#             acc = re.search(pattern, line).group(0)
#             if acc in examp:
#                 print(line)
#         except:
#             pass

In [8]:
# to_add = open("../raw_data/filtered_flipper.txt", "a+")
# with open("../raw_data/example2.txt", "r") as f:
#     i = 0
#     js = []
#     for line in f:
#         try:
#             acc = re.search(pattern, line).group(0)
#             if acc in up:
#                 i += 1
#                 js.append(line)
#         except:
#             pass

# print(f'found {i} proteins')

In [9]:
# File to write the matches
to_add = open("../raw_data/filtered_flipper.js", "a+")
# Iterate the FLIPPER json file
with open("../raw_data/flipper_mobidb_result_2022-07-07T14_09_17.692Z.json", "r") as f:
    i = 0
    for line in f:
        try:
            acc = re.search(pattern, line).group(0)
            if acc in up:
                i += 1
                to_add.write(line)
        except:
            pass
to_add.close()
print(f'found {i} proteins')

found 45 proteins

### Read as DataFrame from json filtered file

In [10]:
fl = pd.read_json('../raw_data/filtered_flipper.js', lines= True)

In [11]:
fl.columns

Index(['acc', 'reviewed', 'gene', 'proteome', 'name', 'length', 'organism',
       'ncbi_taxon_id', 'taxonomy', 'sequence',
       ...
       'derived-observed-mobi-3o78_B', 'derived-observed-mobi-3sg2_A',
       'derived-observed-mobi-3sg3_A', 'derived-observed-mobi-3sg4_A',
       'derived-observed-mobi-3sg5_A', 'derived-observed-mobi-3sg6_A',
       'derived-observed-mobi-3sg7_A', 'derived-observed-mobi-3wlc_A',
       'derived-observed-mobi-3wld_A', 'derived-observed-mobi-4oy4_A'],
      dtype='object', length=5889)

In [12]:
fl.iloc[:, 5000:5100]

,derived-observed-mobi-5csf_C,derived-observed-mobi-5csi_C,derived-observed-mobi-5csj_C,derived-observed-mobi-5csn_C,derived-observed-mobi-5n7d_C,derived-observed-mobi-5n7f_C,derived-observed-mobi-5n7g_C,derived-observed-mobi-5v61_I,derived-observed-mobi-5v62_I,derived-observed-mobi-6twy_C,...,derived-bfactor-mobi-3cpc_B,derived-bfactor-mobi-3dtw_A,derived-bfactor-mobi-3dtw_B,derived-bfactor-mobi-3efl_A,derived-bfactor-mobi-3efl_B,derived-bfactor-mobi-3ewh_A,derived-bfactor-mobi-3kvq_A,derived-bfactor-mobi-3s35_X,derived-bfactor-mobi-3s36_X,derived-bfactor-mobi-3s37_X
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
268,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
fl_sub = fl.iloc[:, :44]

In [14]:
fl_sub.iloc[0]

acc                                                                            Q86WV6
reviewed                                                                         True
gene                                                                           STING1
proteome                                                                  UP000005640
name                                           Stimulator of interferon genes protein
length                                                                            379
organism                                                         Homo sapiens (Human)
ncbi_taxon_id                                                                    9606
taxonomy                            [Eukaryota, Metazoa, Chordata, Craniata, Verte...
sequence                            MPHSSLHPSIPCPRGHGAQKAALVLLSACLVTLWGLGEPPEHTLRY...
localization                        [Endoplasmic reticulum membrane; Multi-pass me...
uniref100                                                            UniRef100_Q86WV6
uniref90                                                              UniRef90_Q86WV6
uniref50                                                              UniRef50_Q86WV6
uniparc                                                                 UPI000000DC5E
ptms                                {'names': ['Phosphoserine; by TBK1', 'Phosphos...
processing                          {'positions': [[1, 190], [153, 340], [238, 241...
prediction-transmembrane-uniprot    {'regions': [[18, 34], [45, 69], [92, 106], [1...
homology-domain-gene3d              {'regions': [[195, 341]], 'content_fraction': ...
homology-domain-pfam                {'regions': [[45, 337]], 'content_fraction': 0...
homology-domain-merge               {'regions': [[45, 341]], 'content_fraction': 0...
prediction-disorder-mobidb_lite     {'regions': [[341, 370]], 'content_count': 30,...
prediction-polar-mobidb_lite_sub    {'regions': [[345, 359]], 'content_count': 15,...
prediction-disorder-th_50           {'regions': [[1, 14], [337, 337], [341, 370], ...
prediction-low_complexity-merge     {'regions': [[47, 67], [98, 109]], 'content_co...
prediction-disorder-iupl            {'regions': [[309, 311], [313, 313], [325, 329...
prediction-disorder-iups            {'regions': [[1, 10], [313, 313], [325, 327], ...
prediction-disorder-espN            {'regions': [[1, 16], [38, 39], [112, 113], [2...
prediction-disorder-espD            {'regions': [[341, 364], [368, 368], [370, 370...
prediction-disorder-espX            {'regions': [[1, 21], [374, 379]], 'content_co...
prediction-disorder-glo             {'regions': [[1, 1], [3, 4], [7, 8], [11, 16],...
prediction-disorder-dis465          {'regions': [[1, 9], [279, 280], [319, 321], [...
prediction-disorder-disHL           {'regions': [[1, 7], [9, 14], [75, 82], [225, ...
prediction-disorder-vsl             {'regions': [[1, 16], [228, 229], [277, 284], ...
prediction-low_complexity-seg       {'regions': [[47, 67], [98, 109]], 'content_co...
prediction-helix-fess               {'scores': [0.003, 0.038, 0.146, 0.187, 0.155,...
prediction-sheet-fess               {'scores': [0.002, 0.018000000000000002, 0.036...
prediction-coil-fess                {'scores': [0.995, 0.9440000000000001, 0.81800...
prediction-rigidity-dynamine        {'scores': [0.387, 0.39, 0.381, 0.384, 0.385, ...
prediction-lip-anchor               {'regions': [[291, 295], [312, 312], [361, 379...
curated-lip-dibs                    {'source_id': 'DI1000276', 'regions': [[342, 3...
curated-disorder-disprot            {'source_id': 'DP01602', 'regions': [[344, 379...
curated-lip-merge                   {'regions': [[342, 379]], 'content_fraction': ...
curated-disorder-merge              {'regions': [[344, 379]], 'content_fraction': ...
Name: 0, dtype: object

## Try to compare with TSV file

In [15]:
fl_tsv = pd.read_csv('../raw_data/mobidb_result_2022-07-11T09_15_38.856Z.tsv', sep= '\t')
fl_tsv.shape

(211353, 6)

In [16]:
fl_tsv.head()

,acc,feature,start..end,content_fraction,content_count,length
0,A0A0D6HTJ9,prediction-transmembrane-uniprot,"21..42,62..89,101..121,150..176,188..214,234.....",0.518919,288,555
1,A0A0D6HTJ9,homology-domain-gene3d,3..524,0.941000,522,555
2,A0A0D6HTJ9,homology-domain-pfam,20..463,0.800000,444,555
3,A0A0D6HTJ9,homology-domain-merge,3..524,0.941000,522,555
4,A0A0D6HTJ9,prediction-disorder-th_50,"1..4,541..555",0.034000,19,555

In [17]:
# Get only proteins with CRE elements
fl_cre = fl_tsv[fl_tsv.acc.isin(cre_dataset.uniprot_acc)]
fl_cre

,acc,feature,start..end,content_fraction,content_count,length
24534,Q86WV6,prediction-transmembrane-uniprot,"18..34,45..69,92..106,117..134",0.197889,75,379
24535,Q86WV6,homology-domain-gene3d,195..341,0.388000,147,379
24536,Q86WV6,homology-domain-pfam,45..337,0.773000,293,379
24537,Q86WV6,homology-domain-merge,45..341,0.784000,297,379
24538,Q86WV6,prediction-disorder-mobidb_lite,341..370,0.079000,30,379
...,...,...,...,...,...,...
208412,P11799,curated-binding_mode_disorder_to_disorder-prio...,2..149,0.078000,148,1906
208413,P11799,derived-lip-priority,1730..1744,0.008000,15,1906
208414,P11799,derived-observed-priority,"1719..1725,1732..1745,1748..1763",0.019000,37,1906
208415,P11799,prediction-disorder-priority,"127..157,309..453,831..881,947..1086,1180..122...",0.240000,457,1906
208416,P11799,prediction-lip-priority,"1..6,78..89,123..127,174..178,205..231,271..27...",0.230000,438,1906

In [18]:
fl_cre.acc.nunique() # ok

45

In [19]:
# Format start and end columns
fl_cre['start..end'] = fl_cre['start..end'].str.split(',')
fl_cre = fl_cre.explode('start..end')
fl_cre

C:\Users\User\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,acc,feature,start..end,content_fraction,content_count,length
24534,Q86WV6,prediction-transmembrane-uniprot,18..34,0.197889,75,379
24534,Q86WV6,prediction-transmembrane-uniprot,45..69,0.197889,75,379
24534,Q86WV6,prediction-transmembrane-uniprot,92..106,0.197889,75,379
24534,Q86WV6,prediction-transmembrane-uniprot,117..134,0.197889,75,379
24535,Q86WV6,homology-domain-gene3d,195..341,0.388000,147,379
...,...,...,...,...,...,...
208416,P11799,prediction-lip-priority,1745..1755,0.230000,438,1906
208416,P11799,prediction-lip-priority,1796..1803,0.230000,438,1906
208416,P11799,prediction-lip-priority,1813..1815,0.230000,438,1906
208416,P11799,prediction-lip-priority,1851..1858,0.230000,438,1906
208416,P11799,prediction-lip-priority,1868..1887,0.230000,438,1906

In [20]:
fl_cre['start..end'][24534]

24534      18..34
24534      45..69
24534     92..106
24534    117..134
Name: start..end, dtype: object

for each feature, sum the (end - start + 1) = content_count.  
content_fraction = content_count / length

In [21]:
# Separate the positions and store in new cols
fl_cre['start..end'] = fl_cre['start..end'].apply(lambda x: re.findall('([0-9]*)..([0-9]*)', x)).apply(lambda x: x[0])
fl_cre['start'] = fl_cre['start..end'].apply(lambda x: x[0]).apply(int)
fl_cre['end'] = fl_cre['start..end'].apply(lambda x: x[1]).apply(int)

In [22]:
fl_cre.groupby(['acc', 'feature']).size().sort_values(ascending= False)

acc     feature
P26663  prediction-disorder-disHL                          64
Q01705  prediction-disorder-glo                            56
P11799  prediction-disorder-disHL                          55
Q9Z0R4  prediction-disorder-disHL                          54
P17210  prediction-disorder-iupl                           53
                                                           ..
Q16620  prediction-low_complexity-merge                     1
Q01705  prediction-signal_peptide-uniprot                   1
        prediction-transmembrane-uniprot                    1
Q04206  curated-binding_mode_disorder_to_disorder-fuzdb     1
P11142  homology-disorder-priority                          1
Length: 1743, dtype: int64

### Example: Q86WV6

In [23]:
Q86WV6 = fl_sub[fl_sub.acc == 'Q86WV6']
Q86WV6

,acc,reviewed,gene,proteome,name,length,organism,ncbi_taxon_id,taxonomy,sequence,...,prediction-low_complexity-seg,prediction-helix-fess,prediction-sheet-fess,prediction-coil-fess,prediction-rigidity-dynamine,prediction-lip-anchor,curated-lip-dibs,curated-disorder-disprot,curated-lip-merge,curated-disorder-merge
0,Q86WV6,True,STING1,UP000005640,Stimulator of interferon genes protein,379,Homo sapiens (Human),9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MPHSSLHPSIPCPRGHGAQKAALVLLSACLVTLWGLGEPPEHTLRY...,...,"{'regions': [[47, 67], [98, 109]], 'content_co...","{'scores': [0.003, 0.038, 0.146, 0.187, 0.155,...","{'scores': [0.002, 0.018000000000000002, 0.036...","{'scores': [0.995, 0.9440000000000001, 0.81800...","{'scores': [0.387, 0.39, 0.381, 0.384, 0.385, ...","{'regions': [[291, 295], [312, 312], [361, 379...","{'source_id': 'DI1000276', 'regions': [[342, 3...","{'source_id': 'DP01602', 'regions': [[344, 379...","{'regions': [[342, 379]], 'content_fraction': ...","{'regions': [[344, 379]], 'content_fraction': ..."
45,Q86WV6,True,STING1,UP000005640,Stimulator of interferon genes protein,379,Homo sapiens (Human),9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MPHSSLHPSIPCPRGHGAQKAALVLLSACLVTLWGLGEPPEHTLRY...,...,"{'regions': [[47, 67], [98, 109]], 'content_co...","{'scores': [0.003, 0.038, 0.146, 0.187, 0.155,...","{'scores': [0.002, 0.018000000000000002, 0.036...","{'scores': [0.995, 0.9440000000000001, 0.81800...","{'scores': [0.387, 0.39, 0.381, 0.384, 0.385, ...","{'regions': [[291, 295], [312, 312], [361, 379...","{'source_id': 'DI1000276', 'regions': [[342, 3...","{'source_id': 'DP01602', 'regions': [[344, 379...","{'regions': [[342, 379]], 'content_fraction': ...","{'regions': [[344, 379]], 'content_fraction': ..."
90,Q86WV6,True,STING1,UP000005640,Stimulator of interferon genes protein,379,Homo sapiens (Human),9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MPHSSLHPSIPCPRGHGAQKAALVLLSACLVTLWGLGEPPEHTLRY...,...,"{'regions': [[47, 67], [98, 109]], 'content_co...","{'scores': [0.003, 0.038, 0.146, 0.187, 0.155,...","{'scores': [0.002, 0.018000000000000002, 0.036...","{'scores': [0.995, 0.9440000000000001, 0.81800...","{'scores': [0.387, 0.39, 0.381, 0.384, 0.385, ...","{'regions': [[291, 295], [312, 312], [361, 379...","{'source_id': 'DI1000276', 'regions': [[342, 3...","{'source_id': 'DP01602', 'regions': [[344, 379...","{'regions': [[342, 379]], 'content_fraction': ...","{'regions': [[344, 379]], 'content_fraction': ..."
135,Q86WV6,True,STING1,UP000005640,Stimulator of interferon genes protein,379,Homo sapiens (Human),9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MPHSSLHPSIPCPRGHGAQKAALVLLSACLVTLWGLGEPPEHTLRY...,...,"{'regions': [[47, 67], [98, 109]], 'content_co...","{'scores': [0.003, 0.038, 0.146, 0.187, 0.155,...","{'scores': [0.002, 0.018000000000000002, 0.036...","{'scores': [0.995, 0.9440000000000001, 0.81800...","{'scores': [0.387, 0.39, 0.381, 0.384, 0.385, ...","{'regions': [[291, 295], [312, 312], [361, 379...","{'source_id': 'DI1000276', 'regions': [[342, 3...","{'source_id': 'DP01602', 'regions': [[344, 379...","{'regions': [[342, 379]], 'content_fraction': ...","{'regions': [[344, 379]], 'content_fraction': ..."
180,Q86WV6,True,STING1,UP000005640,Stimulator of interferon genes protein,379,Homo sapiens (Human),9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MPHSSLHPSIPCPRGHGAQKAALVLLSACLVTLWGLGEPPEHTLRY...,...,"{'regions': [[47, 67], [98, 109]], 'content_co...","{'scores': [0.003, 0.038, 0.146, 0.187, 0.155,...","{'scores': [0.002, 0.018000000000000002, 0.036...","{'scores': [0.995, 0.9440000000000001, 0.81800...","{'scores': [0.387, 0.39, 0.381, 0.384, 0.385, ...","{'regions': [[291, 295], [312, 312], [361, 379...","{'source_id': 'DI1000276', 'regions': [[342, 3...","{'source_id': 'DP01602', 'regions': [[344, 379...","{'regions': [[342, 379]], 'content_fraction': ...","{'regions': [[344, 379]], 'content_fraction': ..."
225,Q86WV6,True,STING1,UP000005640,Stimulator of interferon genes protein,379,Homo sapiens (Human),9606,"[Eukaryota, Metazoa, Chordata, Craniata, Verte...",MPHSSLHPSIPCPRGHGAQKAALVLLSACLVTLWGLGEPPEHTLRY...,...,"{'regions': [[47, 67], [98, 109]], 'content_co...","{'scores': [0.003, 0.038, 0.146, 0.187, 0.155,...","{'scores': [0.002, 0.018000000000000002, 0.036...","{'scores': [0.995, 0.9440000000000001, 0.81800...","{'scores': [0.387, 0.39, 0.381, 0.384, 0.385, ...","{'regions': [[291, 295], [312, 312], [361, 379...","{'source_id': 'DI1000276', 'regions': [[342, 3...","{'source_id': 'DP01602', 'regions': [[344, 379...","{'regions': [[342, 379]], 'content_fraction': ...","{'regions': [[344, 379]], 'content_fraction': ..."

In [24]:
Q86WV6.columns

Index(['acc', 'reviewed', 'gene', 'proteome', 'name', 'length', 'organism',
       'ncbi_taxon_id', 'taxonomy', 'sequence', 'localization', 'uniref100',
       'uniref90', 'uniref50', 'uniparc', 'ptms', 'processing',
       'prediction-transmembrane-uniprot', 'homology-domain-gene3d',
       'homology-domain-pfam', 'homology-domain-merge',
       'prediction-disorder-mobidb_lite', 'prediction-polar-mobidb_lite_sub',
       'prediction-disorder-th_50', 'prediction-low_complexity-merge',
       'prediction-disorder-iupl', 'prediction-disorder-iups',
       'prediction-disorder-espN', 'prediction-disorder-espD',
       'prediction-disorder-espX', 'prediction-disorder-glo',
       'prediction-disorder-dis465', 'prediction-disorder-disHL',
       'prediction-disorder-vsl', 'prediction-low_complexity-seg',
       'prediction-helix-fess', 'prediction-sheet-fess',
       'prediction-coil-fess', 'prediction-rigidity-dynamine',
       'prediction-lip-anchor', 'curated-lip-dibs', 'curated-disorder-disprot',
       'curated-lip-merge', 'curated-disorder-merge'],
      dtype='object')

In [25]:
Q86WV6['prediction-disorder-mobidb_lite'][0]

{'regions': [[341, 370]],
 'content_count': 30,
 'content_fraction': 0.079,
 'scores': [0.75,
  0.625,
  0.75,
  0.75,
  0.625,
  0.625,
  0.75,
  0.625,
  0.625,
  0.5,
  0.5,
  0.5,
  0.5,
  0.5,
  0.375,
  0.375,
  0.125,
  0.125,
  0.125,
  0.125,
  0.125,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.125,
  0.125,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.125,
  0.125,
  0.125,
  0.125,
  0.125,
  0.125,
  0.125,
  0.125,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.125,
  0.125,
  0.25,
  0.25,
  0.125,
  0.125,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.125,
  0.25,
  0.25,
  0.25,
  0.375,
  0.375,
  0.375,
  0.375,
  0.25,
  0.125,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.125,
  0.125,
  0.125,
  0.125,
  0.25,
  0.25,
  0.125,
  0.125,
  0.125,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.25,
  0.125,
  0,
  0.125,
  0.125,
  0.125,
  0,
  0.25,
  0,
  0,
  0.25,
  0.25,
  0.25,
  0.375,
  0.375,
  0.375,
  0.25,
  0,
  0,
  0.25,
  0.25,
  0.25,
  0.125,
  0.25,
  0.125,
  0,
  0,
  0,
  0.125,
  0.125,
  0.375,
  0.5,
  0.375,
  0.375,
  0.25,
  0.625,
  0.625,
  0.75,
  0.75,
  0.75,
  0.75,
  0.75,
  0.75,
  0.75,
  0.75,
  0.875,
  0.875,
  0.875,
  0.75,
  0.75,
  0.75,
  0.75,
  0.75,
  0.75,
  0.75,
  0.625,
  0.625,
  0.625,
  0.625,
  0.5,
  0.5,
  0.5,
  0.625,
  0.5,
  0.75,
  0.375,
  0.5,
  0.375,
  0.5,
  0.625,
  0.875,
  0.75,
  0.875,
  0.875]}

In [26]:
Q86WV6_tsv = fl_cre[fl_cre.acc == 'Q86WV6']
Q86WV6_tsv

,acc,feature,start..end,content_fraction,content_count,length,start,end
24534,Q86WV6,prediction-transmembrane-uniprot,"(18, 34)",0.197889,75,379,18,34
24534,Q86WV6,prediction-transmembrane-uniprot,"(45, 69)",0.197889,75,379,45,69
24534,Q86WV6,prediction-transmembrane-uniprot,"(92, 106)",0.197889,75,379,92,106
24534,Q86WV6,prediction-transmembrane-uniprot,"(117, 134)",0.197889,75,379,117,134
24535,Q86WV6,homology-domain-gene3d,"(195, 341)",0.388000,147,379,195,341
...,...,...,...,...,...,...,...,...
24573,Q86WV6,derived-observed-priority,"(240, 316)",0.715000,271,379,240,316
24573,Q86WV6,derived-observed-priority,"(323, 335)",0.715000,271,379,323,335
24574,Q86WV6,prediction-disorder-priority,"(341, 343)",0.008000,3,379,341,343
24575,Q86WV6,prediction-lip-priority,"(291, 295)",0.016000,6,379,291,295
24575,Q86WV6,prediction-lip-priority,"(312, 312)",0.016000,6,379,312,312

In [27]:
# I have each of the columns from the json file as "feature" in the tsv file

In [28]:
# Searching Q86WV6 in mobidb web: 
# FLIPPER 6nt5_A    LIP [4-20]
# FLIPPER 6nt5_B    LIP [4-20]
# ...
# derived-lip-th_90 == LIP consensus ??
# derived-lip-merge == LIP consensus ??

In [29]:
Q86WV6_tsv[Q86WV6_tsv.feature == 'derived-lip-th_90'] # this is the last row in LIP consensus

,acc,feature,start..end,content_fraction,content_count,length,start,end
24558,Q86WV6,derived-lip-th_90,"(4, 20)",0.066,25,379,4,20
24558,Q86WV6,derived-lip-th_90,"(363, 370)",0.066,25,379,363,370

In [30]:
Q86WV6_tsv[Q86WV6_tsv.feature == 'derived-lip-merge'] # this is the first LIP consensus row (should take this)

,acc,feature,start..end,content_fraction,content_count,length,start,end
24557,Q86WV6,derived-lip-merge,"(4, 20)",0.1,38,379,4,20
24557,Q86WV6,derived-lip-merge,"(359, 379)",0.1,38,379,359,379

## Filter the data by LIP consensus feature

In [31]:
fl_cre[fl_cre.feature == 'derived-lip-merge']

,acc,feature,start..end,content_fraction,content_count,length,start,end
24557,Q86WV6,derived-lip-merge,"(4, 20)",0.100,38,379,4,20
24557,Q86WV6,derived-lip-merge,"(359, 379)",0.100,38,379,359,379
24854,O96013,derived-lip-merge,"(4, 58)",0.093,55,591,4,58
28452,P04637,derived-lip-merge,"(6, 62)",0.384,151,393,6,62
28452,P04637,derived-lip-merge,"(145, 154)",0.384,151,393,145,154
...,...,...,...,...,...,...,...,...
200960,Q01705,derived-lip-merge,"(987, 1016)",0.025,63,2531,987,1016
200960,Q01705,derived-lip-merge,"(1936, 1945)",0.025,63,2531,1936,1945
200960,Q01705,derived-lip-merge,"(2001, 2013)",0.025,63,2531,2001,2013
203192,Q07889,derived-lip-merge,"(1156, 1166)",0.008,11,1333,1156,1166
208406,P11799,derived-lip-merge,"(1730, 1750)",0.011,21,1906,1730,1750

In [32]:
fl_consensus = fl_tsv[fl_tsv.feature == 'derived-lip-merge']

In [33]:
# Separate the positions and store in new cols
fl_consensus['start..end'] = fl_consensus['start..end'].apply(lambda x: re.findall('([0-9]*)..([0-9]*)', x)).apply(lambda x: x[0])
fl_consensus['start'] = fl_consensus['start..end'].apply(lambda x: x[0]).apply(str)
fl_consensus['end'] = fl_consensus['start..end'].apply(lambda x: x[1]).apply(str)
fl_consensus.drop(columns= ["start..end", "feature"], inplace= True) # not needed anymore. feature is always "derived-lip-merge"
fl_consensus.rename(columns= {'acc': 'uniprot_acc'}, inplace= True)
fl_consensus

C:\Users\User\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\User\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\User\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
c:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py:4315: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,
c:\Users\User\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

       uniprot_acc  content_fraction  content_count  length  start    end
16      A0A0D6HTJ9             0.002              1     555      1      1
38      A0A1W2VMW5             0.014              6     434      1      6
59          P0A825             0.019              8     417      1      8
79          Q2YIM3             0.011              5     438      1      5
99          Q8I566             0.014              6     442      1      6
...            ...               ...            ...     ...    ...    ...
211175      Q09666             0.003             16    5890   5654   5669
211215      Q8WXH0             0.002             15    6885   6871   6885
211253      Q03001             0.001             11    7570   7548   7558
211289      Q8NF91             0.003             29    8797   8769   8797
211334      Q8WZ42               NaN              9   34350  24337  24345

[7355 rows x 6 columns]

In [34]:
#fl_consensus.to_csv('../datasets/flipper_consensus.tsv', sep= '\t', header= True, index= False)

# Check overlap with CRE elements

In [36]:
# df with the ranges for each CRE. Rename cols for pyranges
cre_ranges = cre_dataset[['uniprot_acc', 'id_cre', 'start_aa', 'end_aa']].rename(
    columns={'uniprot_acc': 'Chromosome', 'start_aa': 'Start', 'end_aa': 'End'}
)
# As pyranges object
cre_ranges = pr.PyRanges(cre_ranges)

In [43]:
cre_ranges

+--------------+-----------+-----------+-----------+
| Chromosome   | id_cre    | Start     | End       |
| (category)   | (int64)   | (int32)   | (int32)   |
|--------------+-----------+-----------+-----------|
| A8KAM8       | 43        | 1006      | 1106      |
| C8ZE58       | 15        | 604       | 741       |
| O08722       | 124       | 544       | 688       |
| O08808       | 72        | 1180      | 1199      |
| ...          | ...       | ...       | ...       |
| Q64287       | 83        | 410       | 439       |
| Q92985       | 134       | 404       | 466       |
| Q93107       | 14        | 91        | 157       |
| Q94527       | 84        | 640       | 738       |
+--------------+-----------+-----------+-----------+
Unstranded PyRanges object has 168 rows and 4 columns from 151 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [62]:
# LIPs with their ranges
lip_ranges = fl_consensus[['uniprot_acc', 'start', 'end']].rename(
    columns = {'uniprot_acc': 'Chromosome'}
)
lip_ranges.columns = lip_ranges.columns.str.capitalize()
# As pyranges object
lip_ranges = pr.PyRanges(lip_ranges)

In [59]:
lip_ranges

+--------------+-----------+-----------+-----------+
| Chromosome   | Length    | Start     | End       |
| (category)   | (int64)   | (int32)   | (int32)   |
|--------------+-----------+-----------+-----------|
| A0A0A0VBX4   | 95        | 47        | 78        |
| A0A0A1VBK6   | 806       | 214       | 229       |
| A0A0A6ZKT6   | 369       | 66        | 100       |
| A0A0A7HR51   | 547       | 10        | 14        |
| ...          | ...       | ...       | ...       |
| W8XVT2       | 862       | 336       | 369       |
| W9BQC4       | 82        | 52        | 82        |
| X2FE19       | 371       | 49        | 59        |
| X2G898       | 685       | 369       | 377       |
+--------------+-----------+-----------+-----------+
Unstranded PyRanges object has 7,355 rows and 4 columns from 7355 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [57]:
# Count overlaps
overlap = cre_ranges.count_overlaps(lip_ranges, overlap_col = 'overlap_count')

In [58]:
# to dataframe
overlap_df = overlap.as_df()
overlap_df.sort_values("overlap_count")

    Chromosome  id_cre  Start   End  overlap_count
0       A8KAM8      43   1006  1106              0
104     Q8VDP3      60    761  1048              0
105     Q8WUM4      76    709   745              0
106     Q8Y842      68     27    88              0
107     Q9BY11     163    392   442              0
..         ...     ...    ...   ...            ...
33      P10721     114    544   591              1
29      P06782       4    392   495              1
152     Q15418     162    687   706              1
150     Q13625      64    693   901              1
153     Q15691     166    189   268              1

[168 rows x 5 columns]

In [54]:
xx = overlap[overlap.overlap_count > 0]
xx

+--------------+-----------+-----------+-----------+-----------------+
| Chromosome   | id_cre    | Start     | End       | overlap_count   |
| (category)   | (int64)   | (int32)   | (int32)   | (int64)         |
|--------------+-----------+-----------+-----------+-----------------|
| O96013       | 56        | 1         | 130       | 1               |
| P04629       | 97        | 287       | 384       | 1               |
| P06782       | 4         | 392       | 495       | 1               |
| P10721       | 114       | 544       | 591       | 1               |
| ...          | ...       | ...       | ...       | ...             |
| Q13625       | 64        | 693       | 901       | 1               |
| Q15418       | 162       | 687       | 706       | 1               |
| Q15691       | 166       | 189       | 268       | 1               |
| Q63450       | 7         | 285       | 312       | 1               |
+--------------+-----------+-----------+-----------+-----------------+
Unstranded PyRanges object has 12 rows and 5 columns from 12 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [48]:
# Verify
cre_dataset[cre_dataset.uniprot_acc == 'O96013']

,name,uniprot_acc,species,references,module,start_aa,end_aa,dataset,id_cre
55,PAK4,O96013,H. sapiens,"(Ha et al., 2012)",d,1,130,train,56

In [49]:
fl_consensus[fl_consensus.uniprot_acc == 'O96013']

      uniprot_acc  content_fraction  content_count  length start end
24854      O96013             0.093             55     591     4  58

In [65]:
fl_consensus[['uniprot_acc', 'length']]

       uniprot_acc  length
16      A0A0D6HTJ9     555
38      A0A1W2VMW5     434
59          P0A825     417
79          Q2YIM3     438
99          Q8I566     442
...            ...     ...
211175      Q09666    5890
211215      Q8WXH0    6885
211253      Q03001    7570
211289      Q8NF91    8797
211334      Q8WZ42   34350

[7355 rows x 2 columns]

In [69]:
lengths = fl_consensus[['uniprot_acc', 'length']]

In [71]:
xx

+--------------+-----------+-----------+-----------+-----------------+
| Chromosome   | id_cre    | Start     | End       | overlap_count   |
| (category)   | (int64)   | (int32)   | (int32)   | (int64)         |
|--------------+-----------+-----------+-----------+-----------------|
| O96013       | 56        | 1         | 130       | 1               |
| P04629       | 97        | 287       | 384       | 1               |
| P06782       | 4         | 392       | 495       | 1               |
| P10721       | 114       | 544       | 591       | 1               |
| ...          | ...       | ...       | ...       | ...             |
| Q13625       | 64        | 693       | 901       | 1               |
| Q15418       | 162       | 687       | 706       | 1               |
| Q15691       | 166       | 189       | 268       | 1               |
| Q63450       | 7         | 285       | 312       | 1               |
+--------------+-----------+-----------+-----------+-----------------+
Unstranded PyRanges object has 12 rows and 5 columns from 12 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [73]:
# Add protein length
pd.merge([xx, lengths], how= 'left', left_on= 'Chromosome', right_on= 'uniprot_acc')

TypeError: merge() missing 1 required positional argument: 'right'

In [53]:
# Ratio lip/protein_length
xx['ratio'] = (xx.End - xx.Start + 1) /

    Chromosome  id_cre  Start   End  overlap_count
0       A8KAM8      43   1006  1106              0
1       C8ZE58      15    604   741              0
2       O08722     124    544   688              0
3       O08808      72   1180  1199              0
4       O08967      54    251   266              0
..         ...     ...    ...   ...            ...
163     Q63622      86    158   408              0
164     Q64287      83    410   439              0
165     Q92985     134    404   466              0
166     Q93107      14     91   157              0
167     Q94527      84    640   738              0

[168 rows x 5 columns]